### PR TITLE
Fixing #4 - Resize works only with ordering:true

### PR DESCRIPTION
**Pull request by shashank1010**
Handles the issue as mentioned in the issue description

### CODE REVIEW

**Comment by jeffreydwalter** [comment]
Thanks for fixing this!

**Comment by shashank1010** [comment]
You will leave this unmerged?

**Comment by jeffreydwalter** [comment]
Sorry, clicked the wrong button. Merged. Thanks!

**Comment by jeffreydwalter** [comment]
I'm happy to maintain it, but am a little overloaded. If you'd like to
continue contributing I'd be happy to add you as a maintainer.

**Pull request merged**
